### ISSUE TITLE
Some samples will not compile in MonoDevelop 2.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mjacobsen4DFM/google-api-dotnet-client#152]
```
What steps will reproduce the problem?
1.Checkout samples source from repo
2.Load the mono sln in MonoDevelop (get errors related to other .csproj files, 
ignore these)
3.Attempt to compile "Tasks.SimpleOAuth2"

What is the expected output? What do you see instead?
Will not compile, throws an error pointing at the line:
using Google.Apis.Tasks.v1.Data;
"/home/me/Projects/google-api-dotnet-client.samples/Tasks.SimpleOAuth2/Program.c
s(28,28): Error CS0234: The type or namespace name `Data' does not exist in the 
namespace `Google.Apis.Tasks.v1'. Are you missing an assembly reference? 
(CS0234) (Tasks.SimpleOAuth2)"

However when viewing the "Google.Apis.Tasks.v1.dll" reference in the Assembly 
Browser I can see the "Google.Apis.Tasks.v1.Data" namespace just fine. Tried 
compiling the sample in VS2010, had no issues. Also tried in MonoDevelop 2.4 
with Mono 2.6.7 (bundled versions with Natty's repos), it also won't compile 
and complains about the CLR version. I am guessing that is expected though.

There are a few other projects throwing errors related to the Task reference, 
but a whole lot more concerning all kinds of other things. 47 errors in total 
for all of the samples. Again these compile flawlessly in VS2010.

What version of the product are you using? On what operating system?
Ubuntu 11.04
Mono 2.10.5
MonoDevelop 2.6

Mono and MonoDevelop builds are from this ppa: 
https://launchpad.net/~ermshiperete/+archive/monodevelop

google-api-dotnet-client src hg changeset 26:e75059fd6696

Am not truly interested in all of the other samples, but I would have figured 
the basic OAuth2 sample should work with Mono out of the box.
```

Original issue reported on code.google.com by `nsch...@gmail.com` on 28 Sep 2011 at 6:55
